---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todd-test
  labels:
    app: todd-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todd-test
  template:
    metadata:
      labels:
        app: todd-test
    spec:
      containers:
        - name: todd-test
          image: docker.io/parsontodd/todd-test:latest
          ports:
            - containerPort: 8080